let filmsData = [
  {
    "production_year": 2009,
    "id": 4105528,
    "title": "Planet 51",
    "director": "Abad, Javier",
    "director_id": 1975,
    "co_directors": "Abad, Javier|Blanco, Jorge|Martínez, Marcos",
    "co_directors_id": "1516774|1975|233690",
    "genres": "Adventure|Animation|Comedy|Family|Sci-Fi",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2006,
    "id": 3973646,
    "title": "Mission: Impossible III",
    "director": "Abrams, J.J.",
    "director_id": 7718,
    "co_directors": "Abrams, J.J.",
    "co_directors_id": 7718,
    "genres": "Action|Adventure|Thriller",
    "cameras": "Arriflex 235, Panavision C-Series Lenses|Arriflex 435, Panavision Primo, C-Series and Angenieux Optimo Lenses|Panavision Panaflex Millennium XL, Panavision Primo, C-Series and Angenieux Optimo Lenses|Panavision Panaflex Platinum, Panavision Primo, C-Series and Angenieux Optimo Lenses|Sony CineAlta HDC-F950, Zeiss DigiZoom and Fujinon C-Series Lenses",
    "negative_format": "35 mm|Video",
    "film_type": "D|F"
  },
  {
    "production_year": 2009,
    "id": 4272468,
    "title": "Star Trek",
    "director": "Abrams, J.J.",
    "director_id": 7718,
    "co_directors": "Abrams, J.J.",
    "co_directors_id": 7718,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arriflex 435 ES, Panavision Primo Lenses|Panavision Panaflex Millennium XL2, Panavision Primo, C-Series, ATZ and AWZ2 Lenses|Panavision Panaflex Platinum, Panavision Primo, C-Series, ATZ and AWZ2 Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2011,
    "id": 4291293,
    "title": "Super 8",
    "director": "Abrams, J.J.",
    "director_id": 7718,
    "co_directors": "Abrams, J.J.",
    "co_directors_id": 7718,
    "genres": "Mystery|Sci-Fi|Thriller",
    "cameras": "Arriflex 16 SR3, Zeiss Super Speed Lenses|Arriflex 435, Panavision C- and E-Series Lenses|Beaulieu 4008 ZM4|Bell & Howell Eyemo, Panavision C- and E-Series Lenses|Canon 1014XL-S|Panavision Panaflex Millennium XL2, Panavision Primo Anamorphic, C-, E-Series, ATZ and AWZ2 Lenses|Red One MX",
    "negative_format": "16 mm|35 mm|8 mm|Redcode RAW",
    "film_type": "D|F"
  },
  {
    "production_year": 2013,
    "id": 4272595,
    "title": "Star Trek: Into Darkness",
    "director": "Abrams, J.J.",
    "director_id": 7718,
    "co_directors": "Abrams, J.J.",
    "co_directors_id": 7718,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arriflex 435 ES, Panavision Primo, C-, E-Series, ATZ and AWZ2 Lenses|IMAX MSM 9802, Hasselblad Lenses|Iwerks MSM 8870, Hasselblad Lenses|Panavision Panaflex Millennium XL2, Panavision Primo, C-, E-Series, ATZ and AWZ2 Lenses|Red Epic",
    "negative_format": "35 mm|65 mm|Redcode RAW",
    "film_type": "D|F"
  },
  {
    "production_year": 2015,
    "id": 4272821,
    "title": "Star Wars: Episode VII - The Force Awakens",
    "director": "Abrams, J.J.",
    "director_id": 7718,
    "co_directors": "Abrams, J.J.",
    "co_directors_id": 7718,
    "genres": "Action|Adventure|Fantasy|Sci-Fi",
    "cameras": "Arri Alexa|IMAX MKIII, Hasselblad Lenses|IMAX MSM 9802, Hasselblad Lenses|Panavision Panaflex Millennium XL2, Panavision Primo, Retro C-, E-Series, ATZ and AWZ2 Lenses",
    "negative_format": "35 mm|65 mm",
    "film_type": "F"
  },
  {
    "production_year": 2008,
    "id": 4279641,
    "title": "Stories on Human Rights",
    "director": "Abu-Assad, Hany",
    "director_id": 8598,
    "co_directors": "Abramovic, Marina|Abu-Assad, Hany|Ballantyne, Armagan|Bodrov, Sergei|Geffen, Shira|Gonzalez-Foerster, Dominique|Islam, Runa|Jia, Zhangke|Jodice, Francesco|Keret, Etgar|Leccia, Ange|Nair, Murali|Ouedraogo, Idrissa|Rist, Pipilotti|Salles, Walter|Salur, Saman|Sarkis|Schouw, Bram|Serrano, Teresa|Sissako, Abderrahmane|Thomas, Daniela|Trapero, Pablo|Weerasethakul, Apichatpong|Zbanic, Jasmila|de Meaux, Charles",
    "co_directors_id": "1148518|1231220|1358396|1796792|2096322|2117654|2142168|2222258|2416362|243408|2548999|2676352|3137000|3283129|3791116|3994772|4144057|4532289|4620485|4827282|5324739|5354971|5388389|566634|8598",
    "genres": "",
    "cameras": "Arriflex Cameras and Lenses",
    "negative_format": "Super 16",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 3531568,
    "title": "Do Not Forget Me Istanbul",
    "director": "Abu-Assad, Hany",
    "director_id": 8598,
    "co_directors": "Abu-Assad, Hany|Arsenijevic, Stefan|Begic, Aida|Markarian, Iosifina|Nazarian, Eric|Niziris, Stergios|Shargawi, Omar",
    "co_directors_id": "1711145|2179553|2773483|4540983|4883528|8598|96882",
    "genres": "Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 4349118,
    "title": "The Courier",
    "director": "Abu-Assad, Hany",
    "director_id": 8598,
    "co_directors": "Abu-Assad, Hany",
    "co_directors_id": 8598,
    "genres": "Action|Crime|Drama|Mystery|Thriller",
    "cameras": "Red One MX",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2013,
    "id": 4053247,
    "title": "Omar",
    "director": "Abu-Assad, Hany",
    "director_id": 8598,
    "co_directors": "Abu-Assad, Hany",
    "co_directors_id": 8598,
    "genres": "Drama|Romance|Thriller",
    "cameras": "Arri Alexa",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 4590175,
    "title": "Ya tayr el tayer",
    "director": "Abu-Assad, Hany",
    "director_id": 8598,
    "co_directors": "Abu-Assad, Hany",
    "co_directors_id": 8598,
    "genres": "Biography|Comedy|Drama|Music",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2017,
    "id": 4407236,
    "title": "The Mountain Between Us",
    "director": "Abu-Assad, Hany",
    "director_id": 8598,
    "co_directors": "Abu-Assad, Hany",
    "co_directors_id": 8598,
    "genres": "Action|Adventure|Drama|Romance|Thriller",
    "cameras": "Arri Alexa 65, Panavision Sphero 65 Lenses|Arri Alexa Mini, Panavision C-Series Lenses|Arri Alexa SXT, Panavision C-Series Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2009,
    "id": 3229453,
    "title": 9,
    "director": "Acker, Shane",
    "director_id": 10377,
    "co_directors": "Acker, Shane",
    "co_directors_id": 10377,
    "genres": "Action|Adventure|Animation|Drama|Mystery|Sci-Fi|Thriller",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2010,
    "id": 4108881,
    "title": "Plus Minus",
    "director": "Acker, Shane",
    "director_id": 10377,
    "co_directors": "Acker, Shane|Tsirbas, Aristomenis",
    "co_directors_id": "10377|2428107",
    "genres": "Animation|Fantasy|Sci-Fi|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2008,
    "id": 4345058,
    "title": "The Chronicles of Narnia: Prince Caspian",
    "director": "Adamson, Andrew",
    "director_id": 14970,
    "co_directors": "Adamson, Andrew",
    "co_directors_id": 14970,
    "genres": "Action|Adventure|Family|Fantasy",
    "cameras": "Arricam LT, Zeiss Master Prime Lenses|Arricam ST, Zeiss Master Prime Lenses|Arriflex 235, Zeiss Master Prime Lenses|Arriflex 435 Xtreme, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 3440187,
    "title": "Cirque du Soleil: Worlds Away",
    "director": "Adamson, Andrew",
    "director_id": 14970,
    "co_directors": "Adamson, Andrew",
    "co_directors_id": 14970,
    "genres": "Fantasy",
    "cameras": "Arri Alexa|PACE Fusion 3-D",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 3989653,
    "title": "Mr. Pip",
    "director": "Adamson, Andrew",
    "director_id": 14970,
    "co_directors": "Adamson, Andrew",
    "co_directors_id": 14970,
    "genres": "Drama|War",
    "cameras": "Arri Alexa",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 3667091,
    "title": "Gone Baby Gone",
    "director": "Affleck, Ben",
    "director_id": 18760,
    "co_directors": "Affleck, Ben",
    "co_directors_id": 18760,
    "genres": "Crime|Drama|Mystery|Thriller",
    "cameras": "Panavision Panaflex Millennium XL, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4447413,
    "title": "The Town",
    "director": "Affleck, Ben",
    "director_id": 18760,
    "co_directors": "Affleck, Ben",
    "co_directors_id": 18760,
    "genres": "Crime|Drama|Thriller",
    "cameras": "Arriflex 235, Panavision Primo Lenses|Arriflex 435 ES, Panavision Primo and PCZ Lenses|Panavision Panaflex Millennium XL2, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 3309537,
    "title": "Argo",
    "director": "Affleck, Ben",
    "director_id": 18760,
    "co_directors": "Affleck, Ben",
    "co_directors_id": 18760,
    "genres": "Biography|Drama|History|Thriller",
    "cameras": "Arri Alexa Plus, Hawk V-Lite, V-Plus, V-Series, Zeiss Super Speed, Ultra Prime and Angenieux Optimo Lenses|Arricam LT, Hawk V-Lite, V-Plus, V-Series, Zeiss Super Speed, Ultra Prime, Angenieux Optimo and Canon Lenses|Arricam ST, Hawk V-Lite, V-Plus, V-Series, Zeiss Super Speed, Ultra Prime, Angenieux Optimo and Canon Lenses|Arriflex 235, Zeiss Super Speed and Ultra Prime Lenses|Arriflex 35 BL4, Zeiss Super Speed and Ultra Prime Lenses|Arriflex 435, Zeiss Super Speed and Ultra Prime Lenses|Bolex H16 REX-5, Kern-Paillard Switar and Angenieux Lenses|Canon 1014 AZ",
    "negative_format": "16 mm|35 mm|8 mm|Codex",
    "film_type": "D|F"
  },
  {
    "production_year": 2016,
    "id": 3903423,
    "title": "Live by Night",
    "director": "Affleck, Ben",
    "director_id": 18760,
    "co_directors": "Affleck, Ben",
    "co_directors_id": 18760,
    "genres": "Action|Crime|Drama|Thriller",
    "cameras": "Arri Alexa 65, Panavision Sphero 65 and Super 70 Lenses|Red Weapon Dragon",
    "negative_format": "Codex|Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2006,
    "id": 4388766,
    "title": "The Lake House",
    "director": "Agresti, Alejandro",
    "director_id": 21107,
    "co_directors": "Agresti, Alejandro",
    "co_directors_id": 21107,
    "genres": "Drama|Fantasy|Romance",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2013,
    "id": 4029580,
    "title": "No somos animales",
    "director": "Agresti, Alejandro",
    "director_id": 21107,
    "co_directors": "Agresti, Alejandro",
    "co_directors_id": 21107,
    "genres": "Comedy|Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 3953155,
    "title": "Mecánica Popular",
    "director": "Agresti, Alejandro",
    "director_id": 21107,
    "co_directors": "Agresti, Alejandro",
    "co_directors_id": 21107,
    "genres": "Comedy|Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2006,
    "id": 4378966,
    "title": "The Hills Have Eyes",
    "director": "Aja, Alexandre",
    "director_id": 27048,
    "co_directors": "Aja, Alexandre",
    "co_directors_id": 27048,
    "genres": "Horror",
    "cameras": "Arricam ST|Moviecam Compact",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2008,
    "id": 3971264,
    "title": "Mirrors",
    "director": "Aja, Alexandre",
    "director_id": 27048,
    "co_directors": "Aja, Alexandre",
    "co_directors_id": 27048,
    "genres": "Horror|Mystery",
    "cameras": "Arriflex Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4103590,
    "title": "Piranha 3D",
    "director": "Aja, Alexandre",
    "director_id": 27048,
    "co_directors": "Aja, Alexandre",
    "co_directors_id": 27048,
    "genres": "Comedy|Horror|Thriller",
    "cameras": "Arriflex 35-III, Cooke S4 Lenses|Arriflex 435, Cooke S4 Lenses|Panavision Panaflex Platinum, Panavision C-, E-Series, AWZ2 and Angenieux HR Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2013,
    "id": 3721487,
    "title": "Horns",
    "director": "Aja, Alexandre",
    "director_id": 27048,
    "co_directors": "Aja, Alexandre",
    "co_directors_id": 27048,
    "genres": "Drama|Fantasy|Horror|Thriller",
    "cameras": "Arri Alexa Plus, Hawk V-Lite Lenses|Arri Alexa Studio, Hawk V-Lite Lenses",
    "negative_format": "ARRIRAW|Gemini444",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 4323707,
    "title": "The 9th Life of Louis Drax",
    "director": "Aja, Alexandre",
    "director_id": 27048,
    "co_directors": "Aja, Alexandre",
    "co_directors_id": 27048,
    "genres": "Mystery|Thriller",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2017,
    "id": 3409039,
    "title": "Campfire Creepers: The Skull of Sam",
    "director": "Aja, Alexandre",
    "director_id": 27048,
    "co_directors": "Aja, Alexandre",
    "co_directors_id": 27048,
    "genres": "Horror|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 3798724,
    "title": "Jumping the Broom",
    "director": "Akil, Salim",
    "director_id": 28726,
    "co_directors": "Akil, Salim",
    "co_directors_id": 28726,
    "genres": "Comedy|Drama",
    "cameras": "Sony CineAlta F35",
    "negative_format": "Video",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 4263425,
    "title": "Sparkle",
    "director": "Akil, Salim",
    "director_id": 28726,
    "co_directors": "Akil, Salim",
    "co_directors_id": 28726,
    "genres": "Drama|Music",
    "cameras": "Arri Alexa Plus, Zeiss Master Prime and Angenieux Optimo Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2013,
    "id": 3620080,
    "title": "Flat Lake",
    "director": "Allen, Kevin",
    "director_id": 47128,
    "co_directors": "Allen, Kevin",
    "co_directors_id": 47128,
    "genres": "Horror",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2013,
    "id": 4589933,
    "title": "Y Syrcas",
    "director": "Allen, Kevin",
    "director_id": 47128,
    "co_directors": "Allen, Kevin",
    "co_directors_id": 47128,
    "genres": "Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 4516703,
    "title": "Under Milk Wood",
    "director": "Allen, Kevin",
    "director_id": 47128,
    "co_directors": "Allen, Kevin",
    "co_directors_id": 47128,
    "genres": "Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2006,
    "id": 4203806,
    "title": "Scoop",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Crime|Mystery",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2007,
    "id": 3416874,
    "title": "Cassandra's Dream",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Crime|Drama|Romance|Thriller",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2008,
    "id": 4538395,
    "title": "Vicky Cristina Barcelona",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Drama|Romance",
    "cameras": "Arricam LT, Zeiss Master Prime Lenses|Arricam ST, Zeiss Master Prime Lenses|Moviecam Compact, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 4566182,
    "title": "Whatever Works",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Romance",
    "cameras": "Arricam LT, Cooke S4 Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4596731,
    "title": "You Will Meet a Tall Dark Stranger",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Drama|Romance",
    "cameras": "Panavision Panaflex Millennium XL, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2011,
    "id": 3965136,
    "title": "Midnight in Paris",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Fantasy|Romance",
    "cameras": "Arricam LT, Cooke S4, 5/i, Panchro and Angenieux Optimo Lenses|Arricam ST, Cooke S4, 5/i, Panchro and Angenieux Optimo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 4478255,
    "title": "To Rome with Love",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Romance",
    "cameras": "Arricam LT, Cooke 5/i and Speed Panchro Lenses|Arricam ST, Cooke 5/i and Speed Panchro Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2013,
    "id": 3376374,
    "title": "Blue Jasmine",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Drama",
    "cameras": "Arricam LT, Zeiss Master Prime Lenses|Arricam ST, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2014,
    "id": 3929954,
    "title": "Magic in the Moonlight",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Romance",
    "cameras": "Arricam LT, Panavision Primo, C-, D- and E-Series Lenses|Arricam ST, Panavision Primo, C-, D- and E-Series Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2015,
    "id": 3771446,
    "title": "Irrational Man",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Drama",
    "cameras": "Arricam ST, Panavision C-Series Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2016,
    "id": 3405842,
    "title": "Café Society",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Comedy|Drama|Romance",
    "cameras": "Sony CineAlta F65, Cooke S4 Lenses|Sony CineAlta PMW-F55, Cooke S4 Lenses",
    "negative_format": "AXSM|SRMemory",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4582816,
    "title": "Wonder Wheel",
    "director": "Allen, Woody",
    "director_id": 48348,
    "co_directors": "Allen, Woody",
    "co_directors_id": 48348,
    "genres": "Drama",
    "cameras": "Sony CineAlta F65, Cooke S4 and Angenieux Optimo Lenses|Sony CineAlta PMW-F55, Cooke S4 and Angenieux Optimo Lenses",
    "negative_format": "AXSM|SRMemory",
    "film_type": "D"
  },
  {
    "production_year": 2006,
    "id": 4394957,
    "title": "The Little Matchgirl",
    "director": "Allers, Roger",
    "director_id": 48524,
    "co_directors": "Allers, Roger",
    "co_directors_id": 48524,
    "genres": "Animation|Drama|Family|Fantasy|Short",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2006,
    "id": 4062558,
    "title": "Open Season",
    "director": "Allers, Roger",
    "director_id": 48524,
    "co_directors": "Allers, Roger|Culton, Jill|Stacchi, Anthony",
    "co_directors_id": "2274737|4268269|48524",
    "genres": "Adventure|Animation|Comedy|Family",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 4322385,
    "title": "The 2006 Academy Award Nominated Short Films: Animation",
    "director": "Allers, Roger",
    "director_id": 48524,
    "co_directors": "Allers, Roger|Hahn, Don|Kove, Torill|Renaud, Chris|Rydstrom, Gary|Thurmeier, Mike|Tóth, Géza M.",
    "co_directors_id": "1985658|2079432|2389878|2441487|3381510|48524|951486",
    "genres": "",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2014,
    "id": 4422124,
    "title": "The Prophet",
    "director": "Allers, Roger",
    "director_id": 48524,
    "co_directors": "Allers, Roger|Brizzi, Gaëtan|Brizzi, Paul|Gratz, Joan C.|Harib, Mohammed Saeed|Moore, Tomm|Paley, Nina|Plympton, Bill|Sfar, Joann|Socha, Michal",
    "co_directors_id": "1648232|1895707|2173300|292973|292976|3171335|3681891|4370569|4656038|48524",
    "genres": "Animation|Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2008,
    "id": 4212990,
    "title": "Semi-Pro",
    "director": "Alterman, Kent",
    "director_id": 53090,
    "co_directors": "Alterman, Kent",
    "co_directors_id": 53090,
    "genres": "Comedy|Sport",
    "cameras": "Arriflex 435 ES, Panavision Primo, Super Speed MKII and Ultra Speed MKII Lenses|Panavision Panaflex Millennium XL, Panavision Primo, Super Speed MKII and Ultra Speed MKII Lenses|Panavision Panaflex Platinum, Panavision Primo, Super Speed MKII and Ultra Speed MKII Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2006,
    "id": 3247511,
    "title": "A Prairie Home Companion",
    "director": "Altman, Robert",
    "director_id": 53532,
    "co_directors": "Altman, Robert",
    "co_directors_id": 53532,
    "genres": "Comedy|Drama|Music|Musical",
    "cameras": "Sony CineAlta HDW-F900, Fujinon Lenses|Sony HDW-F900",
    "negative_format": "Video",
    "film_type": "D"
  },
  {
    "production_year": 2009,
    "id": 3319134,
    "title": "Ataque de Pánico",
    "director": "Alvarez, Fede",
    "director_id": 54791,
    "co_directors": "Alvarez, Fede",
    "co_directors_id": 54791,
    "genres": "Sci-Fi|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2013,
    "id": 3592596,
    "title": "Evil Dead",
    "director": "Alvarez, Fede",
    "director_id": 54791,
    "co_directors": "Alvarez, Fede",
    "co_directors_id": 54791,
    "genres": "Fantasy|Horror",
    "cameras": "Sony CineAlta F65, Zeiss Master Prime, Fujinon Alura and Angenieux Optimo Lenses",
    "negative_format": "SRMemory",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 3536176,
    "title": "Don't Breathe",
    "director": "Alvarez, Fede",
    "director_id": 54791,
    "co_directors": "Alvarez, Fede",
    "co_directors_id": 54791,
    "genres": "Crime|Horror|Thriller",
    "cameras": "Arri Alexa Plus, Leica Summilux-C, Zeiss Super Speed and Fujinon Alura Lenses|Blackmagic Pocket Cinema Camera, Zeiss Ultra 16 Lenses",
    "negative_format": "SxS Pro",
    "film_type": "D"
  },
  {
    "production_year": 2009,
    "id": 3269786,
    "title": "Agora",
    "director": "Amenábar, Alejandro",
    "director_id": 59035,
    "co_directors": "Amenábar, Alejandro",
    "co_directors_id": 59035,
    "genres": "Adventure|Biography|Drama|History|Romance",
    "cameras": "Arricam LT, Zeiss Master Prime and Master Zoom Lenses|Arricam ST, Zeiss Master Prime and Master Zoom Lenses|Arriflex 235, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2015,
    "id": 4530152,
    "title": "Vale",
    "director": "Amenábar, Alejandro",
    "director_id": 59035,
    "co_directors": "Amenábar, Alejandro",
    "co_directors_id": 59035,
    "genres": "Comedy|Romance|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 4156116,
    "title": "Regression",
    "director": "Amenábar, Alejandro",
    "director_id": 59035,
    "co_directors": "Amenábar, Alejandro",
    "co_directors_id": 59035,
    "genres": "Crime|Drama|Mystery|Thriller",
    "cameras": "Arri Alexa XT, Panavision G-Series, ATZ and AWZ2 Lenses",
    "negative_format": "Codex ARRIRAW",
    "film_type": "D"
  },
  {
    "production_year": 2009,
    "id": 3465303,
    "title": "Creation",
    "director": "Amiel, Jon",
    "director_id": 59698,
    "co_directors": "Amiel, Jon",
    "co_directors_id": 59698,
    "genres": "Biography|Drama|Romance",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2017,
    "id": 3930427,
    "title": "Magnetic",
    "director": "Amiel, Jon",
    "director_id": 59698,
    "co_directors": "Amiel, Jon",
    "co_directors_id": 59698,
    "genres": "Drama|Romance",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2008,
    "id": 4217867,
    "title": "Sex Drive",
    "director": "Anders, Sean",
    "director_id": 63679,
    "co_directors": "Anders, Sean",
    "co_directors_id": 63679,
    "genres": "Adventure|Comedy|Romance",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 4321397,
    "title": "That's My Boy",
    "director": "Anders, Sean",
    "director_id": 63679,
    "co_directors": "Anders, Sean",
    "co_directors_id": 63679,
    "genres": "Comedy",
    "cameras": "Red Epic, Panavision Primo Lenses",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2014,
    "id": 3721703,
    "title": "Horrible Bosses 2",
    "director": "Anders, Sean",
    "director_id": 63679,
    "co_directors": "Anders, Sean",
    "co_directors_id": 63679,
    "genres": "Comedy|Crime",
    "cameras": "Arri Alexa XT, Leica Summilux-C and Angenieux Optimo Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 3476624,
    "title": "Daddy's Home",
    "director": "Anders, Sean",
    "director_id": 63679,
    "co_directors": "Anders, Sean",
    "co_directors_id": 63679,
    "genres": "Comedy|Family",
    "cameras": "Arri Alexa XT, Leica Summilux-C Lenses",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 3476627,
    "title": "Daddy's Home 2",
    "director": "Anders, Sean",
    "director_id": 63679,
    "co_directors": "Anders, Sean",
    "co_directors_id": 63679,
    "genres": "Comedy",
    "cameras": "Arri Alexa|RED Weapon 8K",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2008,
    "id": 4490939,
    "title": "Transsiberian",
    "director": "Anderson, Brad",
    "director_id": 64771,
    "co_directors": "Anderson, Brad",
    "co_directors_id": 64771,
    "genres": "Crime|Drama|Mystery|Thriller",
    "cameras": "Arricam LT, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4532037,
    "title": "Vanishing on 7th Street",
    "director": "Anderson, Brad",
    "director_id": 64771,
    "co_directors": "Anderson, Brad",
    "co_directors_id": 64771,
    "genres": "Horror|Mystery|Thriller",
    "cameras": "Red One Camera",
    "negative_format": "Video",
    "film_type": "D"
  },
  {
    "production_year": 2013,
    "id": 4341461,
    "title": "The Call",
    "director": "Anderson, Brad",
    "director_id": 64771,
    "co_directors": "Anderson, Brad",
    "co_directors_id": 64771,
    "genres": "Crime|Thriller",
    "cameras": "Arri Alexa, Angenieux Optimo Lenses|Phantom Flex",
    "negative_format": "SxS Pro",
    "film_type": "D"
  },
  {
    "production_year": 2014,
    "id": 3573523,
    "title": "Eliza Graves",
    "director": "Anderson, Brad",
    "director_id": 64771,
    "co_directors": "Anderson, Brad",
    "co_directors_id": 64771,
    "genres": "Drama|Horror|Mystery|Thriller",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 4462665,
    "title": "There Will Be Blood",
    "director": "Anderson, Paul Thomas",
    "director_id": 67374,
    "co_directors": "Anderson, Paul Thomas",
    "co_directors_id": 67374,
    "genres": "Drama|History",
    "cameras": "Panavision Panaflex Millennium XL, Panavision C-, E-Series, Super High Speed, SP and Pathé Lenses|Panavision Panaflex Platinum, Panavision C-, E-Series, Super High Speed and SP Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 4402801,
    "title": "The Master",
    "director": "Anderson, Paul Thomas",
    "director_id": 67374,
    "co_directors": "Anderson, Paul Thomas",
    "co_directors_id": 67374,
    "genres": "Drama",
    "cameras": "Panavision 65 HR Camera, Panavision System 65, Hasselblad and Kowa Super 66 Fisheye Lenses|Panavision Panaflex Millennium XL2, Panavision Ultra Speed Z-Series MKII and Zeiss Jena Lenses|Panavision Panaflex System 65 Studio, Panavision System 65, Hasselblad and Kowa Super 66 Fisheye Lenses",
    "negative_format": "35 mm|65 mm",
    "film_type": "F"
  },
  {
    "production_year": 2014,
    "id": 3762616,
    "title": "Inherent Vice",
    "director": "Anderson, Paul Thomas",
    "director_id": 67374,
    "co_directors": "Anderson, Paul Thomas",
    "co_directors_id": 67374,
    "genres": "Comedy|Crime|Drama|Mystery|Romance",
    "cameras": "Panavision Panaflex Millennium XL2, Panavision Super Speed MKII and Cooke Panchro Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2015,
    "id": 3799615,
    "title": "Junun",
    "director": "Anderson, Paul Thomas",
    "director_id": 67374,
    "co_directors": "Anderson, Paul Thomas",
    "co_directors_id": 67374,
    "genres": "Documentary|Music",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4097771,
    "title": "Phantom Thread",
    "director": "Anderson, Paul Thomas",
    "director_id": 67374,
    "co_directors": "Anderson, Paul Thomas",
    "co_directors_id": 67374,
    "genres": "Drama",
    "cameras": "Panavision Panaflex Millennium XL2, Panavision Ultra Speed Z-Series MKII Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2008,
    "id": 3496754,
    "title": "Death Race",
    "director": "Anderson, Paul W.S.",
    "director_id": 67376,
    "co_directors": "Anderson, Paul W.S.",
    "co_directors_id": 67376,
    "genres": "Action|Sci-Fi|Thriller",
    "cameras": "Arricam LT|Arricam ST|Arriflex 235|Arriflex 35 III|Arriflex 435|Arriflex 535",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4160697,
    "title": "Resident Evil: Afterlife",
    "director": "Anderson, Paul W.S.",
    "director_id": 67376,
    "co_directors": "Anderson, Paul W.S.",
    "co_directors_id": 67376,
    "genres": "Action|Adventure|Horror|Sci-Fi",
    "cameras": "PACE Fusion 3-D|Phantom HD Camera, Zeiss Master Prime and Angenieux Optimo Lenses|Sony CineAlta F35, Zeiss Master Prime and Angenieux Optimo Lenses",
    "negative_format": "Digital|HDCAM",
    "film_type": "D"
  },
  {
    "production_year": 2011,
    "id": 4446134,
    "title": "The Three Musketeers",
    "director": "Anderson, Paul W.S.",
    "director_id": 67376,
    "co_directors": "Anderson, Paul W.S.",
    "co_directors_id": 67376,
    "genres": "Action|Adventure|Romance",
    "cameras": "Arri Alexa, Zeiss Master Prime Lenses|PACE Fusion 3-D|Red One MX, Zeiss Master Prime Lenses|Weisscam HS-2",
    "negative_format": "Digital|Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 4160710,
    "title": "Resident Evil: Retribution",
    "director": "Anderson, Paul W.S.",
    "director_id": 67376,
    "co_directors": "Anderson, Paul W.S.",
    "co_directors_id": 67376,
    "genres": "Action|Horror|Sci-Fi|Thriller",
    "cameras": "3Ality Technica Atom 3D Rig|Red Epic",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2014,
    "id": 4112601,
    "title": "Pompeii",
    "director": "Anderson, Paul W.S.",
    "director_id": 67376,
    "co_directors": "Anderson, Paul W.S.",
    "co_directors_id": 67376,
    "genres": "Action|Adventure|Drama|History|Romance",
    "cameras": "Red Epic, Zeiss Ultra Prime Lenses",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 4160712,
    "title": "Resident Evil: The Final Chapter",
    "director": "Anderson, Paul W.S.",
    "director_id": 67376,
    "co_directors": "Anderson, Paul W.S.",
    "co_directors_id": 67376,
    "genres": "Action|Horror|Sci-Fi|Thriller",
    "cameras": "Red Epic Dragon, Zeiss Ultra Prime and Angenieux Optimo Lenses",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 3954311,
    "title": "Meet the Robinsons",
    "director": "Anderson, Stephen J.",
    "director_id": 67912,
    "co_directors": "Anderson, Stephen J.",
    "co_directors_id": 67912,
    "genres": "Adventure|Animation|Comedy|Family|Sci-Fi",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2011,
    "id": 4578206,
    "title": "Winnie the Pooh",
    "director": "Anderson, Stephen J.",
    "director_id": 67912,
    "co_directors": "Anderson, Stephen J.|Hall, Don",
    "co_directors_id": "67912|956137",
    "genres": "Adventure|Animation|Comedy|Family|Musical",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2016,
    "id": 4287482,
    "title": "Sugar",
    "director": "Anderson, Stephen J.",
    "director_id": 67912,
    "co_directors": "Anderson, Stephen J.",
    "co_directors_id": 67912,
    "genres": "Comedy|Drama|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2016,
    "id": 4287485,
    "title": "Sugar",
    "director": "Anderson, Stephen J.",
    "director_id": 67912,
    "co_directors": "Anderson, Stephen J.",
    "co_directors_id": 67912,
    "genres": "Comedy|Drama|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 3723954,
    "title": "Hotel Chevalier",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Drama|Romance|Short",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2007,
    "id": 4351766,
    "title": "The Darjeeling Limited",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Adventure|Comedy|Drama",
    "cameras": "Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 3603122,
    "title": "Fantastic Mr. Fox",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Adventure|Animation|Comedy|Crime|Family",
    "cameras": "Nikon D3, Nikon and Cooke Varotal Lenses",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 3462713,
    "title": "Cousin Ben Troop Screening with Jason Schwartzman",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Comedy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 3982508,
    "title": "Moonrise Kingdom: Animated Book Short",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes|De Vita, Christian",
    "co_directors_id": "5337274|68256",
    "genres": "Animation|Comedy|Fantasy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 3982507,
    "title": "Moonrise Kingdom",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Adventure|Comedy|Drama|Romance",
    "cameras": "Aaton A-Minima, Zeiss Super Speed and Canon Lenses|Aaton Xterà, Zeiss Super Speed and Canon Lenses",
    "negative_format": "16 mm",
    "film_type": "F"
  },
  {
    "production_year": 2013,
    "id": 3417124,
    "title": "Castello Cavalcanti",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Comedy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2013,
    "id": 4119112,
    "title": "Prada: Candy",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes|Coppola, Roman",
    "co_directors_id": "482388|68256",
    "genres": "Short",
    "cameras": "Arricam LT|Arricam ST",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2014,
    "id": 4373630,
    "title": "The Grand Budapest Hotel",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Adventure|Comedy|Drama",
    "cameras": "Arricam ST, Technovision/Cooke, Cooke S4, Varotal and Angenieux Optimo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2016,
    "id": 3450932,
    "title": "Come Together: A Fashion Picture in Motion",
    "director": "Anderson, Wes",
    "director_id": 68256,
    "co_directors": "Anderson, Wes",
    "co_directors_id": 68256,
    "genres": "Comedy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 4541898,
    "title": "Violet",
    "director": "Andrews, Mark",
    "director_id": 71454,
    "co_directors": "Andrews, Mark",
    "co_directors_id": 71454,
    "genres": "Drama|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 3387921,
    "title": "Brave",
    "director": "Andrews, Mark",
    "director_id": 71454,
    "co_directors": "Andrews, Mark|Chapman, Brenda|Purcell, Steve",
    "co_directors_id": "1931677|2898381|71454",
    "genres": "Adventure|Animation|Comedy|Family|Fantasy|Thriller",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4179319,
    "title": "Rough Night",
    "director": "Aniello, Lucia",
    "director_id": 2714242,
    "co_directors": "Aniello, Lucia",
    "co_directors_id": 2714242,
    "genres": "Comedy",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2017,
    "id": 4573966,
    "title": "Why You've Never Met the 4th Haim Sister",
    "director": "Aniello, Lucia",
    "director_id": 2714242,
    "co_directors": "Aniello, Lucia",
    "co_directors_id": 2714242,
    "genres": "Comedy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2014,
    "id": 4338192,
    "title": "The Boxtrolls",
    "director": "Annable, Graham",
    "director_id": 75813,
    "co_directors": "Annable, Graham|Stacchi, Anthony",
    "co_directors_id": "2274737|75813",
    "genres": "Adventure|Animation|Comedy|Family|Fantasy",
    "cameras": "Canon EOS 5D Mark III",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 4186368,
    "title": "Sa majesté Minor",
    "director": "Annaud, Jean-Jacques",
    "director_id": 75908,
    "co_directors": "Annaud, Jean-Jacques",
    "co_directors_id": 75908,
    "genres": "Comedy|Fantasy",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 3368601,
    "title": "Black Gold",
    "director": "Annaud, Jean-Jacques",
    "director_id": 75908,
    "co_directors": "Annaud, Jean-Jacques",
    "co_directors_id": 75908,
    "genres": "Adventure|Drama|History",
    "cameras": "Arricam LT, Cooke S4 and Angenieux Optimo Lenses|Arriflex 435, Cooke S4 and Angenieux Optimo Lenses|Canon EOS 5D Mark II|Canon EOS 7D",
    "negative_format": "35 mm|Video",
    "film_type": "D|F"
  },
  {
    "production_year": 2015,
    "id": 3873530,
    "title": "Le dernier loup",
    "director": "Annaud, Jean-Jacques",
    "director_id": 75908,
    "co_directors": "Annaud, Jean-Jacques",
    "co_directors_id": 75908,
    "genres": "Adventure",
    "cameras": "Arri Alexa Studio, Angenieux Optimo Lenses|Red Epic, Zeiss Ultra Prime and Angenieux Optimo Lenses|Screenplane rigs",
    "negative_format": "Codex|Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 3902737,
    "title": "Little Red Wagon",
    "director": "Anspaugh, David",
    "director_id": 76865,
    "co_directors": "Anspaugh, David",
    "co_directors_id": 76865,
    "genres": "Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 4529333,
    "title": "Vacancy",
    "director": "Antal, Nimród",
    "director_id": 76996,
    "co_directors": "Antal, Nimród",
    "co_directors_id": 76996,
    "genres": "Horror|Thriller",
    "cameras": "Panavision Panaflex Millennium XL, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 3310672,
    "title": "Armored",
    "director": "Antal, Nimród",
    "director_id": 76996,
    "co_directors": "Antal, Nimród",
    "co_directors_id": 76996,
    "genres": "Action|Crime|Thriller",
    "cameras": "Arriflex 435 ES, Panavision Primo Lenses|Panavision Panaflex Millennium XL2, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4120219,
    "title": "Predators",
    "director": "Antal, Nimród",
    "director_id": 76996,
    "co_directors": "Antal, Nimród",
    "co_directors_id": 76996,
    "genres": "Action|Adventure|Sci-Fi|Thriller",
    "cameras": "Panavision Genesis HD Camera, Panavision Primo Lenses",
    "negative_format": "Video",
    "film_type": "D"
  },
  {
    "production_year": 2013,
    "id": 3961051,
    "title": "Metallica Through the Never",
    "director": "Antal, Nimród",
    "director_id": 76996,
    "co_directors": "Antal, Nimród",
    "co_directors_id": 76996,
    "genres": "Music",
    "cameras": "Arri Alexa|Arri Alexa M, Zeiss Ultra Prime and Angenieux Optimo Lenses|Arri Alexa Plus, Zeiss Ultra Prime and Angenieux Optimo Lenses|Red Epic, Zeiss Ultra Prime and Angenieux Optimo Lenses",
    "negative_format": "Codex|Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 3254560,
    "title": "A Viszkis",
    "director": "Antal, Nimród",
    "director_id": 76996,
    "co_directors": "Antal, Nimród",
    "co_directors_id": 76996,
    "genres": "Action|Adventure|Crime|Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2010,
    "id": 3399894,
    "title": "Burlesque",
    "director": "Antin, Steve",
    "director_id": 78407,
    "co_directors": "Antin, Steve",
    "co_directors_id": 78407,
    "genres": "Drama|Music|Musical|Romance",
    "cameras": "Arricam LT, Cooke S4 and Panchro Lenses|Arriflex 235, Cooke S4 and Panchro Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2007,
    "id": 3825125,
    "title": "Knocked Up",
    "director": "Apatow, Judd",
    "director_id": 81426,
    "co_directors": "Apatow, Judd",
    "co_directors_id": 81426,
    "genres": "Comedy|Romance",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 3641731,
    "title": "Funny People",
    "director": "Apatow, Judd",
    "director_id": 81426,
    "co_directors": "Apatow, Judd",
    "co_directors_id": 81426,
    "genres": "Comedy|Drama",
    "cameras": "Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 3734485,
    "title": "I Am Harry Potter",
    "director": "Apatow, Judd",
    "director_id": 81426,
    "co_directors": "Apatow, Judd",
    "co_directors_id": 81426,
    "genres": "Comedy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 4465396,
    "title": "This Is 40",
    "director": "Apatow, Judd",
    "director_id": 81426,
    "co_directors": "Apatow, Judd",
    "co_directors_id": 81426,
    "genres": "Comedy|Romance",
    "cameras": "Arri Alexa, Panavision Primo Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 4489355,
    "title": "Trainwreck",
    "director": "Apatow, Judd",
    "director_id": 81426,
    "co_directors": "Apatow, Judd",
    "co_directors_id": 81426,
    "genres": "Comedy|Drama|Romance",
    "cameras": "Arricam LT, Cooke 5/i Lenses|Arricam ST, Cooke 5/i Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2017,
    "id": 3950569,
    "title": "May It Last: A Portrait of the Avett Brothers",
    "director": "Apatow, Judd",
    "director_id": 81426,
    "co_directors": "Apatow, Judd|Bonfiglio, Michael",
    "co_directors_id": "251582|81426",
    "genres": "Documentary|Music",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2006,
    "id": 3286179,
    "title": "Amazing Grace",
    "director": "Apted, Michael",
    "director_id": 83029,
    "co_directors": "Apted, Michael",
    "co_directors_id": 83029,
    "genres": "Biography|Drama|History|Romance",
    "cameras": "Arriflex Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2007,
    "id": 4420183,
    "title": "The Power of the Game",
    "director": "Apted, Michael",
    "director_id": 83029,
    "co_directors": "Apted, Michael",
    "co_directors_id": 83029,
    "genres": "Documentary|Drama|Sport",
    "cameras": "",
    "negative_format": "HD",
    "film_type": "D"
  },
  {
    "production_year": 2010,
    "id": 4345073,
    "title": "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "director": "Apted, Michael",
    "director_id": 83029,
    "co_directors": "Apted, Michael",
    "co_directors_id": 83029,
    "genres": "Adventure|Family|Fantasy",
    "cameras": "Sony CineAlta F23",
    "negative_format": "Video",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 3426535,
    "title": "Chasing Mavericks",
    "director": "Apted, Michael",
    "director_id": 83029,
    "co_directors": "Apted, Michael|Hanson, Curtis",
    "co_directors_id": "83029|971412",
    "genres": "Biography|Drama|Sport",
    "cameras": "Arri Alexa|Red Epic",
    "negative_format": "Codex|Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2014,
    "id": 3351940,
    "title": "Bending the Light",
    "director": "Apted, Michael",
    "director_id": 83029,
    "co_directors": "Apted, Michael",
    "co_directors_id": 83029,
    "genres": "Biography|Documentary|Family|History|News",
    "cameras": "Canon Cinema Lenses|Canon EOS C500",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4521318,
    "title": "Unlocked",
    "director": "Apted, Michael",
    "director_id": 83029,
    "co_directors": "Apted, Michael",
    "co_directors_id": 83029,
    "genres": "Action|Drama|Mystery|Thriller",
    "cameras": "Arri Alexa|Arri Alexa XT|Hawk V-Lite Anamorphic Lenses|Hawk V-Plus Anamorphic Lenses|Red Epic",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2010,
    "id": 3840474,
    "title": "L'imbroglio nel lenzuolo",
    "director": "Arau, Alfonso",
    "director_id": 85114,
    "co_directors": "Arau, Alfonso",
    "co_directors_id": 85114,
    "genres": "Comedy|Romance",
    "cameras": "Arriflex 535B",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2007,
    "id": 3491025,
    "title": "De fortabte sjæles ø",
    "director": "Arcel, Nikolaj",
    "director_id": 86281,
    "co_directors": "Arcel, Nikolaj",
    "co_directors_id": 86281,
    "genres": "Action|Adventure|Family|Fantasy",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4193856,
    "title": "Sandheden om mænd",
    "director": "Arcel, Nikolaj",
    "director_id": 86281,
    "co_directors": "Arcel, Nikolaj",
    "co_directors_id": 86281,
    "genres": "Comedy|Drama|Romance",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 3577650,
    "title": "En kongelig affære",
    "director": "Arcel, Nikolaj",
    "director_id": 86281,
    "co_directors": "Arcel, Nikolaj",
    "co_directors_id": 86281,
    "genres": "Biography|Drama|History|Romance",
    "cameras": "Arricam ST, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2017,
    "id": 4352065,
    "title": "The Dark Tower",
    "director": "Arcel, Nikolaj",
    "director_id": 86281,
    "co_directors": "Arcel, Nikolaj",
    "co_directors_id": 86281,
    "genres": "Action|Adventure|Fantasy|Horror|Sci-Fi|Western",
    "cameras": "ARRI Rental Prime 65 lenses|ARRI Rental Vintage 765 lenses|Arri Alexa 65|Arri Alexa XT",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2006,
    "id": 4519701,
    "title": "Unfolding Florence: The Many Lives of Florence Broadhurst",
    "director": "Armstrong, Gillian",
    "director_id": 2724776,
    "co_directors": "Armstrong, Gillian",
    "co_directors_id": 2724776,
    "genres": "Documentary",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 3496194,
    "title": "Death Defying Acts",
    "director": "Armstrong, Gillian",
    "director_id": 2724776,
    "co_directors": "Armstrong, Gillian",
    "co_directors_id": 2724776,
    "genres": "Drama|Romance|Thriller",
    "cameras": "Panavision Panaflex Millennium XL, Panavision E-Series and Hylén Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 3918578,
    "title": "Love, Lust & Lies",
    "director": "Armstrong, Gillian",
    "director_id": 2724776,
    "co_directors": "Armstrong, Gillian",
    "co_directors_id": 2724776,
    "genres": "Documentary",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 4582144,
    "title": "Women He's Undressed",
    "director": "Armstrong, Gillian",
    "director_id": 2724776,
    "co_directors": "Armstrong, Gillian",
    "co_directors_id": 2724776,
    "genres": "Biography|Documentary",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2006,
    "id": 4367720,
    "title": "The Fountain",
    "director": "Aronofsky, Darren",
    "director_id": 94955,
    "co_directors": "Aronofsky, Darren",
    "co_directors_id": 94955,
    "genres": "Drama|Sci-Fi",
    "cameras": "Panavision Panaflex Millennium XL, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2008,
    "id": 4460282,
    "title": "The Wrestler",
    "director": "Aronofsky, Darren",
    "director_id": 94955,
    "co_directors": "Aronofsky, Darren",
    "co_directors_id": 94955,
    "genres": "Drama|Sport",
    "cameras": "Arriflex 416, Zeiss Ultra 16 and Angenieux Optimo Lenses",
    "negative_format": "16 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 3369949,
    "title": "Black Swan",
    "director": "Aronofsky, Darren",
    "director_id": 94955,
    "co_directors": "Aronofsky, Darren",
    "co_directors_id": 94955,
    "genres": "Drama|Thriller",
    "cameras": "Arriflex 16 SR3, Zeiss Ultra 16 Lenses|Arriflex 416, Zeiss Ultra 16 Lenses|Canon EOS 1D Mark IV, Canon L-Series Lenses|Canon EOS 7D, Canon L-Series Lenses",
    "negative_format": "16 mm|Digital",
    "film_type": "D|F"
  },
  {
    "production_year": 2014,
    "id": 4030292,
    "title": "Noah",
    "director": "Aronofsky, Darren",
    "director_id": 94955,
    "co_directors": "Aronofsky, Darren",
    "co_directors_id": 94955,
    "genres": "Action|Adventure|Drama",
    "cameras": "Arri Alexa Plus, Zeiss Ultra Prime and Angenieux Optimo Lenses|Arricam LT, Zeiss Ultra Prime and Angenieux Optimo Lenses|Arriflex 435, Angenieux Optimo Lenses|Canon EOS 5D Mark II",
    "negative_format": "35 mm|Codex",
    "film_type": "D|F"
  },
  {
    "production_year": 2017,
    "id": 4449379,
    "title": "The Truth Is Hard to Find the New York Times: Brian Denton",
    "director": "Aronofsky, Darren",
    "director_id": 94955,
    "co_directors": "Aronofsky, Darren",
    "co_directors_id": 94955,
    "genres": "Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2017,
    "id": 3985816,
    "title": "Mother!",
    "director": "Aronofsky, Darren",
    "director_id": 94955,
    "co_directors": "Aronofsky, Darren",
    "co_directors_id": 94955,
    "genres": "Drama|Horror|Mystery",
    "cameras": "Arricam LT, Zeiss Ultra Prime Lenses|Arriflex 416 Plus, Zeiss Ultra 16 Lenses|Red Epic Dragon, Zeiss Ultra Prime Lenses",
    "negative_format": "16 mm|35 mm|Redcode RAW",
    "film_type": "D|F"
  },
  {
    "production_year": 2009,
    "id": 4598887,
    "title": "Youth in Revolt",
    "director": "Arteta, Miguel",
    "director_id": 97458,
    "co_directors": "Arteta, Miguel",
    "co_directors_id": 97458,
    "genres": "Comedy|Drama|Romance",
    "cameras": "Phantom HD Camera|Sony CineAlta F35",
    "negative_format": "Video",
    "film_type": "D"
  },
  {
    "production_year": 2009,
    "id": 3432913,
    "title": "Chinatown Film Project",
    "director": "Arteta, Miguel",
    "director_id": 97458,
    "co_directors": "Arteta, Miguel|Chang, Patty|Cohen, Jem|Fukunaga, Cary|Gray, Bradley Rust|Kim, So Yong|Pollard, Samuel D.|Silver, Shelly|Troche, Rose|Wang, Wayne|Wong, Richard",
    "co_directors_id": "1900270|2208665|2531267|4017282|4354570|4431029|457356|4734870|4785884|801574|97458",
    "genres": "Biography|Comedy|Drama|Family|History|Musical|Romance|Sport",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 3420115,
    "title": "Cedar Rapids",
    "director": "Arteta, Miguel",
    "director_id": 97458,
    "co_directors": "Arteta, Miguel",
    "co_directors_id": 97458,
    "genres": "Comedy",
    "cameras": "Arriflex D-21, Cooke S4 Lenses",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2014,
    "id": 3276088,
    "title": "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
    "director": "Arteta, Miguel",
    "director_id": 97458,
    "co_directors": "Arteta, Miguel",
    "co_directors_id": 97458,
    "genres": "Comedy|Family",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2017,
    "id": 3345281,
    "title": "Beatriz at Dinner",
    "director": "Arteta, Miguel",
    "director_id": 97458,
    "co_directors": "Arteta, Miguel",
    "co_directors_id": 97458,
    "genres": "Comedy|Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 3663071,
    "title": "Gnomeo & Juliet",
    "director": "Asbury, Kelly",
    "director_id": 99703,
    "co_directors": "Asbury, Kelly",
    "co_directors_id": 99703,
    "genres": "Animation|Comedy|Family|Romance",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4249051,
    "title": "Smurfs: The Lost Village",
    "director": "Asbury, Kelly",
    "director_id": 99703,
    "co_directors": "Asbury, Kelly",
    "co_directors_id": 99703,
    "genres": "Adventure|Animation|Comedy|Family|Fantasy",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 3444429,
    "title": "Closing the Ring",
    "director": "Attenborough, Richard",
    "director_id": 107485,
    "co_directors": "Attenborough, Richard",
    "co_directors_id": 107485,
    "genres": "Drama|Romance",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2014,
    "id": 3890741,
    "title": "Let Love Last",
    "director": "Avildsen, John G.",
    "director_id": 113567,
    "co_directors": "Avildsen, John G.",
    "co_directors_id": 113567,
    "genres": "Drama|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 3229327,
    "title": "88 Minutes",
    "director": "Avnet, Jon",
    "director_id": 113894,
    "co_directors": "Avnet, Jon",
    "co_directors_id": 113894,
    "genres": "Crime|Drama|Mystery|Thriller",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2008,
    "id": 4167394,
    "title": "Righteous Kill",
    "director": "Avnet, Jon",
    "director_id": 113894,
    "co_directors": "Avnet, Jon",
    "co_directors_id": 113894,
    "genres": "Action|Crime|Drama|Mystery|Thriller",
    "cameras": "Arricam LT, Cooke S4 and Angenieux Optimo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2017,
    "id": 4467916,
    "title": "Three Christs",
    "director": "Avnet, Jon",
    "director_id": 113894,
    "co_directors": "Avnet, Jon",
    "co_directors_id": 113894,
    "genres": "Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2008,
    "id": 4282503,
    "title": "Street Kings",
    "director": "Ayer, David",
    "director_id": 115673,
    "co_directors": "Ayer, David",
    "co_directors_id": 115673,
    "genres": "Action|Crime|Drama|Thriller",
    "cameras": "Arricam LT, Zeiss Master Prime Lenses|Arriflex 235, Zeiss Master Prime Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 3579369,
    "title": "End of Watch",
    "director": "Ayer, David",
    "director_id": 115673,
    "co_directors": "Ayer, David",
    "co_directors_id": 115673,
    "genres": "Action|Crime|Drama|Thriller",
    "cameras": "Canon EOS 5D Mark II, Canon Lenses|Canon EOS 7D, Canon Lenses|Canon XA-10|GoPro HD Hero|Silicon Imaging SI-2K 'Nano', Zeiss Ultra Prime Lenses|Silicon Imaging SI-2K Mini, Zeiss Ultra Prime Lenses",
    "negative_format": "CineForm RAW|Video",
    "film_type": "D"
  },
  {
    "production_year": 2014,
    "id": 3642220,
    "title": "Fury",
    "director": "Ayer, David",
    "director_id": 115673,
    "co_directors": "Ayer, David",
    "co_directors_id": 115673,
    "genres": "Action|Drama|War",
    "cameras": "Panavision Panaflex Millennium XL2, Panavision C-, G-Series, ATZ and AWZ2 Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2014,
    "id": 4187040,
    "title": "Sabotage",
    "director": "Ayer, David",
    "director_id": 115673,
    "co_directors": "Ayer, David",
    "co_directors_id": 115673,
    "genres": "Action|Crime|Drama|Thriller",
    "cameras": "Arri Alexa M, Angenieux Optimo and Optimo DP Lenses|Arri Alexa Plus, Angenieux Optimo and Optimo DP Lenses|Arri Alexa, Angenieux Optimo and Optimo DP Lenses|Silicon Imaging SI-2K 'Nano'|View Factor Novo 2K",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 4288055,
    "title": "Suicide Squad",
    "director": "Ayer, David",
    "director_id": 115673,
    "co_directors": "Ayer, David",
    "co_directors_id": 115673,
    "genres": "Action|Adventure|Fantasy|Sci-Fi",
    "cameras": "Arriflex 435 ES, Panavision G-Series Lenses|Panavision Panaflex Millennium XL2, Panavision E- and G-Series Lenses|Phantom Flex4K, Panavision G-Series Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2017,
    "id": 3391207,
    "title": "Bright",
    "director": "Ayer, David",
    "director_id": 115673,
    "co_directors": "Ayer, David",
    "co_directors_id": 115673,
    "genres": "Action|Crime|Fantasy|Sci-Fi|Thriller",
    "cameras": "Arri Alexa 65|Arri Alexa Mini|Arri Alexa XT|Blackmagic URSA Mini|Red Weapon Helium|Sony Action Cam 4K",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 3713322,
    "title": "Hitman: Agent 47",
    "director": "Bach, Aleksander",
    "director_id": 5324246,
    "co_directors": "Bach, Aleksander",
    "co_directors_id": 5324246,
    "genres": "Action|Adventure|Crime|Thriller",
    "cameras": "Arri Alexa XT Plus, Zeiss Master Anamorphic and Master Prime Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 4494283,
    "title": "Trickle Dickle Down",
    "director": "Bakshi, Ralph",
    "director_id": 132982,
    "co_directors": "Bakshi, Ralph",
    "co_directors_id": 132982,
    "genres": "Animation|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 3867785,
    "title": "Last Days of Coney Island",
    "director": "Bakshi, Ralph",
    "director_id": 132982,
    "co_directors": "Bakshi, Ralph",
    "co_directors_id": 132982,
    "genres": "Adventure|Animation|Drama|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2010,
    "id": 3717666,
    "title": "Home Makeover",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Tourneux, Samuel",
    "co_directors_id": "134269|4964658",
    "genres": "Animation|Comedy|Family|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2010,
    "id": 3336347,
    "title": "Banana",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Tourneux, Samuel",
    "co_directors_id": "134269|4964658",
    "genres": "Animation|Comedy|Family|Sci-Fi|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2010,
    "id": 4065446,
    "title": "Orientation Day",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Tourneux, Samuel",
    "co_directors_id": "134269|4964658",
    "genres": "Animation|Comedy|Family|Sci-Fi|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 4396531,
    "title": "The Lorax",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Renaud, Chris",
    "co_directors_id": "134269|1985658",
    "genres": "Adventure|Animation|Comedy|Drama|Family|Fantasy|Musical",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 3969738,
    "title": "Minions: Mini-Movie - Competition",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Soret, Julien",
    "co_directors_id": "134269|5391427",
    "genres": "Action|Animation|Comedy|Family|Sci-Fi|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 3969733,
    "title": "Minions",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Coffin, Pierre",
    "co_directors_id": "134269|456106",
    "genres": "Action|Adventure|Animation|Comedy|Family",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 3511624,
    "title": "Despicable Me 3",
    "director": "Balda, Kyle",
    "director_id": 134269,
    "co_directors": "Balda, Kyle|Coffin, Pierre|Guillon, Eric",
    "co_directors_id": "134269|456106|5347873",
    "genres": "Action|Adventure|Animation|Comedy|Family|Sci-Fi",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 4181686,
    "title": "Ruin",
    "director": "Ball, Wes",
    "director_id": 136693,
    "co_directors": "Ball, Wes",
    "co_directors_id": 136693,
    "genres": "Action|Animation|Sci-Fi|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2014,
    "id": 4403245,
    "title": "The Maze Runner",
    "director": "Ball, Wes",
    "director_id": 136693,
    "co_directors": "Ball, Wes",
    "co_directors_id": 136693,
    "genres": "Action|Mystery|Sci-Fi|Thriller",
    "cameras": "Arri Alexa, Cooke S4 and Angenieux Optimo Lenses|Red Epic, Cooke S4 and Angenieux Optimo Lenses|Silicon Imaging SI-2K",
    "negative_format": "Gemini 4|Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 3951243,
    "title": "Maze Runner: The Scorch Trials",
    "director": "Ball, Wes",
    "director_id": 136693,
    "co_directors": "Ball, Wes",
    "co_directors_id": 136693,
    "genres": "Action|Sci-Fi|Thriller",
    "cameras": "Arri Alexa XT Plus, Cooke S4 and Angenieux Optimo Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 3299840,
    "title": "Animal Crackers",
    "director": "Bancroft, Tony",
    "director_id": 139993,
    "co_directors": "Bancroft, Tony|Maestro, Jaime|Sava, Scott Christian",
    "co_directors_id": "139993|1462608|2123135",
    "genres": "Adventure|Animation|Comedy|Family|Fantasy",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2010,
    "id": 3270994,
    "title": "AIDS: We Did It!",
    "director": "Banks, Elizabeth",
    "director_id": 2752288,
    "co_directors": "Banks, Elizabeth",
    "co_directors_id": 2752288,
    "genres": "Comedy|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 3800013,
    "title": "Just a Little Heart Attack",
    "director": "Banks, Elizabeth",
    "director_id": 2752288,
    "co_directors": "Banks, Elizabeth",
    "co_directors_id": 2752288,
    "genres": "Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2013,
    "id": 3987520,
    "title": "Movie 43",
    "director": "Banks, Elizabeth",
    "director_id": 2752288,
    "co_directors": "Banks, Elizabeth|Brill, Steven|Carr, Steve|Cundieff, Rusty|Duffy, James|Dunne, Griffin|Farrelly, Peter|Forsberg, Patrik|Graham, Will|Gunn, James|Odenkirk, Bob|Ratner, Brett|van Tulleken, Jonathan",
    "co_directors_id": "1768045|1965919|2752288|290537|373527|4295961|4323829|4353443|4703432|517911|654632|725014|935159",
    "genres": "Comedy|Romance",
    "cameras": "Red One MX, Zeiss Ultra Prime and Angenieux Optimo Lenses",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2015,
    "id": 4104358,
    "title": "Pitch Perfect 2",
    "director": "Banks, Elizabeth",
    "director_id": 2752288,
    "co_directors": "Banks, Elizabeth",
    "co_directors_id": 2752288,
    "genres": "Comedy|Music",
    "cameras": "Arri Alexa Plus, Panavision Primo and PCZ Lenses",
    "negative_format": "SxS Pro",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 4304720,
    "title": "Take It",
    "director": "Barclay, Paris",
    "director_id": 147492,
    "co_directors": "Barclay, Paris",
    "co_directors_id": 147492,
    "genres": "Drama|Romance|Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2006,
    "id": 3434353,
    "title": "Choking Man",
    "director": "Barron, Steve",
    "director_id": 156943,
    "co_directors": "Barron, Steve",
    "co_directors_id": 156943,
    "genres": "Drama",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2009,
    "id": 4282438,
    "title": "Street Fighter: The Legend of Chun-Li",
    "director": "Bartkowiak, Andrzej",
    "director_id": 159277,
    "co_directors": "Bartkowiak, Andrzej",
    "co_directors_id": 159277,
    "genres": "Action|Crime|Thriller",
    "cameras": "Arricam LT, Zeiss Ultra Prime, Angenieux Optimo and Canon Lenses|Arriflex 235, Zeiss Ultra Prime, Angenieux Optimo and Canon Lenses|Arriflex 35-3, Zeiss Ultra Prime, Angenieux Optimo and Canon Lenses|Arriflex 435, Zeiss Ultra Prime, Angenieux Optimo and Canon Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2017,
    "id": 3950347,
    "title": "Maximum Impact",
    "director": "Bartkowiak, Andrzej",
    "director_id": 159277,
    "co_directors": "Bartkowiak, Andrzej",
    "co_directors_id": 159277,
    "genres": "Action|Comedy",
    "cameras": "Hawk V-Lite Anamorphic Lenses|Hawk V-Plus Anamorphic Lenses|Red Epic|Sony A7s",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 3283897,
    "title": "Altar Rock",
    "director": "Bartkowiak, Andrzej",
    "director_id": 159277,
    "co_directors": "Bartkowiak, Andrzej",
    "co_directors_id": 159277,
    "genres": "Thriller",
    "cameras": "Hawk Anamorphic Lenses",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2007,
    "id": 4490108,
    "title": "Transformers",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arriflex 235, Panavision C-Series Lenses|Arriflex 35 IIC, Panavision C-Series Lenses|Arriflex 435 Xtreme, Panavision C- and E-Series Lenses|Bell & Howell Eyemo, Panavision C-Series Lenses|Panavision Panaflex Millennium XL, Panavision C-, E-Series, Angenieux HR and Cooke Lenses|Panavision Panaflex Platinum, Panavision C-, E-Series, Angenieux HR and Cooke Lenses|Photo-Sonics 4ER, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 4490143,
    "title": "Transformers: Revenge of the Fallen",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arriflex 235, Panavision C-, E- and G-Series Lenses|Arriflex 435 ES, Panavision C-, E-, G-Series, ATZ, AWZ2 and Angenieux Optimo Lenses|IMAX MKIII, Hasselblad Lenses|IMAX MSM 9802, Hasselblad Lenses|Iwerks IW5A, Hasselblad Lenses|Panavision Panaflex Platinum, Panavision C-, E-, G-Series, ATZ, AWZ2, Angenieux Optimo and Canon Lenses",
    "negative_format": "35 mm|65 mm",
    "film_type": "F"
  },
  {
    "production_year": 2011,
    "id": 4490130,
    "title": "Transformers: Dark of the Moon",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arri Alexa, Zeiss Master Prime Lenses|Arriflex 235, Panavision G-Series Lenses|Panavision Panaflex Lightweight, Panavision C-, E- and G-Series Lenses|Panavision Panaflex Platinum, Panavision C-, E- and G-Series Lenses|Red One MX|Silicon Imaging SI-2K|Sony CineAlta F35, Zeiss Master Prime Lenses",
    "negative_format": "35 mm|ARRIRAW|Redcode RAW|Uncompressed Digital",
    "film_type": "D|F"
  },
  {
    "production_year": 2013,
    "id": 4075540,
    "title": "Pain & Gain",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Comedy|Crime|Drama|Thriller",
    "cameras": "Canon EOS 7D|GoPro HD Hero|Panavision Panaflex Millennium XL2, Panavision C-Series Lenses|Phantom HD Gold, Panavision C-Series Lenses|Red Epic, Panavision C-Series Lenses",
    "negative_format": "35 mm|Redcode RAW|Video",
    "film_type": "D|F"
  },
  {
    "production_year": 2014,
    "id": 4490126,
    "title": "Transformers: Age of Extinction",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arriflex 235, Panavision C- and G-Series Lenses|Panavision Panaflex Millennium XL2, Panavision C- and G-Series Lenses|Phantom 65 Gold, IMAX 3-D Lenses|Red Epic Dragon, Panavision C-, G-Series and Leica Summilux Lenses",
    "negative_format": "35 mm|IMAX Digital 3-D|Redcode RAW",
    "film_type": "D|F"
  },
  {
    "production_year": 2016,
    "id": 3216427,
    "title": "13 Hours",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Drama|History|Thriller|War",
    "cameras": "GoPro HERO3+|Red Epic Dragon, Panavision Primo, E-, G-Series, ATZ and Vantage One Lenses|Sony Alpha 7s",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4490150,
    "title": "Transformers: The Last Knight",
    "director": "Bay, Michael",
    "director_id": 170648,
    "co_directors": "Bay, Michael",
    "co_directors_id": 170648,
    "genres": "Action|Adventure|Sci-Fi",
    "cameras": "Arri Alexa IMAX (dual-strip 3-D), Hasselblad Prime 65 and Hawk 65 Lenses|Arriflex 416 Plus, Hawk V-Lite16 1.3x Lenses|Red Epic Dragon, Panavision C-Series Lenses|Red Weapon Dragon, Panavision C-Series Lenses|Red Weapon Helium, Panavision C-Series and Vantage One Lenses",
    "negative_format": "16 mm|Codex|IMAX Digital 3-D|Redcode RAW",
    "film_type": "D|F"
  },
  {
    "production_year": 2010,
    "id": 3245860,
    "title": "A Nightmare on Elm Street",
    "director": "Bayer, Samuel",
    "director_id": 170992,
    "co_directors": "Bayer, Samuel",
    "co_directors_id": 170992,
    "genres": "Crime|Drama|Horror|Mystery|Thriller",
    "cameras": "Panavision Panaflex Millennium XL2, Panavision E-, G-Series, ATZ and AWZ2 Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 3765839,
    "title": "Installing Love",
    "director": "Bayer, Samuel",
    "director_id": 170992,
    "co_directors": "Bayer, Samuel",
    "co_directors_id": 170992,
    "genres": "Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 4352389,
    "title": "The David Documentary",
    "director": "Bayer, Samuel",
    "director_id": 170992,
    "co_directors": "Bayer, Samuel",
    "co_directors_id": 170992,
    "genres": "Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2013,
    "id": 3370030,
    "title": "Black Tongue",
    "director": "Bayer, Samuel",
    "director_id": 170992,
    "co_directors": "Bayer, Samuel",
    "co_directors_id": 170992,
    "genres": "Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2017,
    "id": 4392959,
    "title": "The LEGO Ninjago Movie",
    "director": "Bean, Charlie",
    "director_id": 173279,
    "co_directors": "Bean, Charlie|Fisher, Paul|Logan, Bob",
    "co_directors_id": "1414439|173279|4815888",
    "genres": "Action|Adventure|Animation|Comedy|Family",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2016,
    "id": 4181880,
    "title": "Rules Don't Apply",
    "director": "Beatty, Warren",
    "director_id": 174841,
    "co_directors": "Beatty, Warren",
    "co_directors_id": 174841,
    "genres": "Comedy|Drama|Romance",
    "cameras": "Arri Alexa XT, Panavision Super Speed MKII and Ultra Speed MKII Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 4575414,
    "title": "Wild Hogs",
    "director": "Becker, Walt",
    "director_id": 178053,
    "co_directors": "Becker, Walt",
    "co_directors_id": 178053,
    "genres": "Action|Adventure|Comedy",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 4051536,
    "title": "Old Dogs",
    "director": "Becker, Walt",
    "director_id": 178053,
    "co_directors": "Becker, Walt",
    "co_directors_id": 178053,
    "genres": "Comedy|Family",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2015,
    "id": 3284425,
    "title": "Alvin and the Chipmunks: The Road Chip",
    "director": "Becker, Walt",
    "director_id": 178053,
    "co_directors": "Becker, Walt",
    "co_directors_id": 178053,
    "genres": "Adventure|Animation|Comedy|Family|Fantasy|Music",
    "cameras": "Red Epic Dragon, Cooke S4 and Angenieux Optimo Lenses",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2006,
    "id": 3531206,
    "title": "Dnevnoy dozor",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur",
    "co_directors_id": 182889,
    "genres": "Action|Fantasy|Thriller",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2007,
    "id": 3771382,
    "title": "Ironiya sudby. Prodolzhenie",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur",
    "co_directors_id": 182889,
    "genres": "Comedy|Romance",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2008,
    "id": 4553361,
    "title": "Wanted",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur",
    "co_directors_id": 182889,
    "genres": "Action|Crime|Fantasy|Thriller",
    "cameras": "Arriflex 235, Panavision Primo Lenses|Arriflex 435, Panavision Primo Lenses|Panavision Panaflex Cameras, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2010,
    "id": 4595028,
    "title": "Yolki",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur|Chevazhevskiy, Yaroslav|Jonynas, Ignas|Kiselev, Dmitriy|Voytinskiy, Aleksandr",
    "co_directors_id": "1173319|182889|2510715|421479|4860258",
    "genres": "Comedy",
    "cameras": "Red One Camera",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2012,
    "id": 3259848,
    "title": "Abraham Lincoln: Vampire Hunter",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur",
    "co_directors_id": 182889,
    "genres": "Action|Fantasy|Horror|Western",
    "cameras": "Arri Alexa, Zeiss Ultra Prime and Fujinon Alura Lenses|Arriflex 435, Zeiss Ultra Prime Lenses|Phantom Flex, Zeiss Ultra Prime Lenses",
    "negative_format": "35 mm|Codex ARRIRAW",
    "film_type": "D|F"
  },
  {
    "production_year": 2014,
    "id": 4595029,
    "title": "Yolki 1914",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur|Bykov, Yuriy|Karpilovskiy, Aleksandr|Kiselev, Dmitriy|Kott, Aleksandr",
    "co_directors_id": "1206081|1286375|182889|336576|4860258",
    "genres": "Comedy",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2016,
    "id": 4595032,
    "title": "Yolki 5",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur|Dzhendubaev, Indar|Kott, Aleksandr|Perelman, Vadim|Shavkero, Andrei",
    "co_directors_id": "1286375|182889|1855514|4807684|5388864",
    "genres": "Comedy",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2016,
    "id": 3351804,
    "title": "Ben-Hur",
    "director": "Bekmambetov, Timur",
    "director_id": 182889,
    "co_directors": "Bekmambetov, Timur",
    "co_directors_id": 182889,
    "genres": "Action|Adventure|Drama|History",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2006,
    "id": 4274791,
    "title": "Stay Alive",
    "director": "Bell, William Brent",
    "director_id": 186153,
    "co_directors": "Bell, William Brent",
    "co_directors_id": 186153,
    "genres": "Horror|Thriller",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 4354804,
    "title": "The Devil Inside",
    "director": "Bell, William Brent",
    "director_id": 186153,
    "co_directors": "Bell, William Brent",
    "co_directors_id": 186153,
    "genres": "Horror",
    "cameras": "",
    "negative_format": "Digital",
    "film_type": "D"
  },
  {
    "production_year": 2013,
    "id": 4562052,
    "title": "Wer",
    "director": "Bell, William Brent",
    "director_id": 186153,
    "co_directors": "Bell, William Brent",
    "co_directors_id": 186153,
    "genres": "Action|Horror|Mystery|Thriller",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2016,
    "id": 4338202,
    "title": "The Boy",
    "director": "Bell, William Brent",
    "director_id": 186153,
    "co_directors": "Bell, William Brent",
    "co_directors_id": 186153,
    "genres": "Horror|Mystery|Thriller",
    "cameras": "Arri Alexa XT Plus, Vantage One Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 3988722,
    "title": "Mr. Bean's Holiday",
    "director": "Bendelack, Steve",
    "director_id": 190830,
    "co_directors": "Bendelack, Steve",
    "co_directors_id": 190830,
    "genres": "Comedy|Family",
    "cameras": "Arricam LT, Cooke S4 and Angenieux Optimo Lenses|Arricam ST, Cooke S4 and Angenieux Optimo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2013,
    "id": 4377173,
    "title": "The Harry Hill Movie",
    "director": "Bendelack, Steve",
    "director_id": 190830,
    "co_directors": "Bendelack, Steve",
    "co_directors_id": 190830,
    "genres": "Adventure|Comedy|Musical",
    "cameras": "Arri Alexa Studio, Zeiss Master Prime and Fujinon Alura Lenses|Arri Alexa XT Plus, Zeiss Master Prime and Fujinon Alura Lenses",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 3607360,
    "title": "Feast of Love",
    "director": "Benton, Robert",
    "director_id": 197437,
    "co_directors": "Benton, Robert",
    "co_directors_id": 197437,
    "genres": "Drama|Romance",
    "cameras": "Panavision Panaflex Gold II, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2006,
    "id": 4348172,
    "title": "The Contract",
    "director": "Beresford, Bruce",
    "director_id": 199084,
    "co_directors": "Beresford, Bruce",
    "co_directors_id": 199084,
    "genres": "Action|Crime|Drama|Thriller",
    "cameras": "",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 3940327,
    "title": "Mao's Last Dancer",
    "director": "Beresford, Bruce",
    "director_id": 199084,
    "co_directors": "Beresford, Bruce",
    "co_directors_id": 199084,
    "genres": "Biography|Drama|Music|Romance",
    "cameras": "Panavision Cameras and Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2011,
    "id": 4089791,
    "title": "Peace, Love, & Misunderstanding",
    "director": "Beresford, Bruce",
    "director_id": 199084,
    "co_directors": "Beresford, Bruce",
    "co_directors_id": 199084,
    "genres": "Comedy|Drama|Music|Romance",
    "cameras": "Red One MX",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 3988931,
    "title": "Mr. Church",
    "director": "Beresford, Bruce",
    "director_id": 199084,
    "co_directors": "Beresford, Bruce",
    "co_directors_id": 199084,
    "genres": "Comedy|Drama",
    "cameras": "Arri Alexa",
    "negative_format": "",
    "film_type": "D"
  },
  {
    "production_year": 2007,
    "id": 4387792,
    "title": "The Kingdom",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Action|Drama|Thriller",
    "cameras": "Arriflex 235, Panavision Primo Lenses|Arriflex 435, Panavision Primo Lenses|Panavision Genesis HD Camera, Panavision Primo Lenses|Panavision Panaflex Millennium XL, Panavision Primo and Angenieux Optimo Lenses|Panavision Panaflex Millennium, Panavision Primo and Angenieux Optimo Lenses",
    "negative_format": "35 mm|Video",
    "film_type": "D|F"
  },
  {
    "production_year": 2008,
    "id": 3686394,
    "title": "Hancock",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Action|Crime|Drama|Sci-Fi",
    "cameras": "Arriflex 235, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2012,
    "id": 3342907,
    "title": "Battleship",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Action|Adventure|Sci-Fi|Thriller",
    "cameras": "Arriflex 435 ES, Panavision Primo, E-, G-Series, ATZ and AWZ2 Lenses|Panavision Panaflex Lightweight, Panavision Primo, E-, G-Series, ATZ and AWZ2 Lenses|Panavision Panaflex Millennium XL2, Panavision Primo, E-, G-Series, ATZ and AWZ2 Lenses|Panavision Panaflex Platinum, Panavision Primo, E-, G-Series, ATZ and AWZ2 Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2013,
    "id": 3907573,
    "title": "Lone Survivor",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Action|Biography|Drama|Thriller|War",
    "cameras": "Red Epic, Fujinon Premier, Premier Cabrio and Angenieux Optimo Lenses",
    "negative_format": "Redcode RAW",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 3499124,
    "title": "Deepwater Horizon",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Action|Drama|Thriller",
    "cameras": "Arri Alexa 65, Hasselblad Prime 65 Lenses|Arri Alexa XT, Leica Summicron-C and Summilux-C Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2016,
    "id": 4087910,
    "title": "Patriots Day",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Crime|Drama|History|Thriller",
    "cameras": "Arri Alexa XT Plus, Leica Summilux-C and Angenieux Optimo Lenses",
    "negative_format": "Codex",
    "film_type": "D"
  },
  {
    "production_year": 2017,
    "id": 4524436,
    "title": "Untitled Rihanna Documentary",
    "director": "Berg, Peter",
    "director_id": 199670,
    "co_directors": "Berg, Peter",
    "co_directors_id": 199670,
    "genres": "Documentary",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 4512932,
    "title": "Un monstre à Paris",
    "director": "Bergeron, Bibo",
    "director_id": 200739,
    "co_directors": "Bergeron, Bibo",
    "co_directors_id": 200739,
    "genres": "Adventure|Animation|Comedy|Fantasy|Music|Romance",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2015,
    "id": 3629569,
    "title": "Foudroyés",
    "director": "Bergeron, Bibo",
    "director_id": 200739,
    "co_directors": "Bergeron, Bibo",
    "co_directors_id": 200739,
    "genres": "Short",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2010,
    "id": 3895320,
    "title": "Life as We Know It",
    "director": "Berlanti, Greg",
    "director_id": 202857,
    "co_directors": "Berlanti, Greg",
    "co_directors_id": 202857,
    "genres": "Comedy|Drama|Romance",
    "cameras": "Panavision Panaflex Millennium XL, Panavision Primo Lenses|Panavision Panaflex Platinum, Panavision Primo Lenses",
    "negative_format": "35 mm",
    "film_type": "F"
  },
  {
    "production_year": 2009,
    "id": 3468463,
    "title": "Crude",
    "director": "Berlinger, Joe",
    "director_id": 203112,
    "co_directors": "Berlinger, Joe",
    "co_directors_id": 203112,
    "genres": "Documentary",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2011,
    "id": 4080959,
    "title": "Paradise Lost 3: Purgatory",
    "director": "Berlinger, Joe",
    "director_id": 203112,
    "co_directors": "Berlinger, Joe|Sinofsky, Bruce",
    "co_directors_id": "203112|2220507",
    "genres": "Crime|Documentary",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  },
  {
    "production_year": 2012,
    "id": 4516524,
    "title": "Under African Skies",
    "director": "Berlinger, Joe",
    "director_id": 203112,
    "co_directors": "Berlinger, Joe",
    "co_directors_id": 203112,
    "genres": "Biography|Documentary|History|Music",
    "cameras": "",
    "negative_format": "",
    "film_type": "U"
  }
]

module.exports = filmsData;
